version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=lab4
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    command: java -jar app.jar
    volumes:
      - .:/code
    depends_on:
      - postgres

volumes:
  postgres_data: