version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=lab
      - POSTGRES_PASSWORD=lab1
      - POSTGRES_DB=postgres
    ports:
      - "6432:5432"
    restart: unless-stopped